name: Tests
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  tests:
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler: latest
          bundler-cache: true
          ruby-version: 3.1
      - name: Setup
        run: bundle exec rake --trace db:create db:schema:load db:seed
      - name: Test
        run: bundle exec rake spec
